# Generated by Django 5.1.6 on 2025-02-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_core', '0002_customers_user_alter_customers_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='email',
        ),
        migrations.AddField(
            model_name='customers',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
